#!/usr/bin/env python 
import urllib2, sys 
urlstr = sys.argv[1] 
fname = urlstr.split('/')[-1] 
response = urllib2.urlopen(urlstr) 
f = open(fname, "w") 
f.write(response.read()) 
f.close() 
print "written " + fname